fix: space bug when in pip
Ajaxy/telegram-tt pull request #221
Opened 2023-01-19 09:07 UTC by iib0011

fixes #220

2023-01-19 20:41 UTC, Ajaxy requested changes

2023-01-19 20:41 UTC, Ajaxy commented on src/hooks/usePictureInPicture.ts
> +    video.addEventListener('leavepictureinpicture', () => { onLeave(); setIsInPictureInPicture(false); });
Introducing an arrow function here will break `removeEventListener`.

2023-01-19 20:54 UTC, iib0011 commented on src/hooks/usePictureInPicture.ts
> +    video.addEventListener('leavepictureinpicture', () => { onLeave(); setIsInPictureInPicture(false); });
fixed

2023-01-19 20:56 UTC, Ajaxy requested changes

2023-01-19 20:56 UTC, Ajaxy commented on src/hooks/usePictureInPicture.ts
>      // PIP is not supported in PWA on iOS, despite being detected
This comment now looks non-relevant.

2023-01-19 20:56 UTC, Ajaxy commented on src/hooks/usePictureInPicture.ts
> +    video.addEventListener('enterpictureinpicture', onEnterInternal);
It would make sense to move the new functions above this line.

2023-01-19 21:18 UTC, iib0011 commented on src/hooks/usePictureInPicture.ts
> +    video.addEventListener('enterpictureinpicture', onEnterInternal);
done

2023-01-22 16:12 UTC, Ajaxy approved these changes

2023-01-22 16:12 UTC, Ajaxy commented on src/hooks/usePictureInPicture.ts
> +      onEnter(); setIsInPictureInPicture(true);
```suggestion
      onEnter();
      setIsInPictureInPicture(true);
```

2023-01-22 16:12 UTC, Ajaxy commented on src/hooks/usePictureInPicture.ts
> +      onLeave(); setIsInPictureInPicture(false);
```suggestion
      onLeave();
      setIsInPictureInPicture(false);
```

2023-01-22 16:18 UTC, merged

2023-01-22 16:19 UTC, Ajaxy commented
Merged, thank you!