Ability to move current reply to a new draft
Ajaxy/telegram-tt pull request #358
Opened 2024-04-01 20:03 UTC by dmitrykabanovdev

2024-04-03 10:22 UTC, maxdestor commented
1.  Клик на плашку должен открывать контекстное меню, а не только показывать сообщение. 

https://github.com/Ajaxy/telegram-tt/assets/47010047/bac93808-2a28-46d4-86c2-9f604c019c91

2. Поменять в форваде название на Forward to Another Chat вместо Change Recipient 
![изображение](https://github.com/Ajaxy/telegram-tt/assets/47010047/460e22ee-effb-40f9-9ecd-317000e5982d)

3. Расширить функционал меню до таких пунктов:
![изображение](https://github.com/Ajaxy/telegram-tt/assets/47010047/4106556d-e45f-44f6-832b-d300564e49fb)
![изображение](https://github.com/Ajaxy/telegram-tt/assets/47010047/7bf86aa7-ee3f-4322-afff-3d3eead1d32d)

2024-04-09 08:39 UTC, maxdestor commented
1. Клик на само сообщение в реплае не должно скроллить до сообщения, только при нажатии на Show in Chat

https://github.com/Ajaxy/telegram-tt/assets/47010047/f3aa6acd-1093-4e1b-aefc-6a27bfcef6b9

2. При реплае стикером в другой чат, превью стикера не загружается

https://github.com/Ajaxy/telegram-tt/assets/47010047/a2cef1b5-d638-4c8f-ae19-2c6258a3211b

3. Не хватает картинки для Show Message и для Remove Quote

<img width="238" alt="Screenshot 2024-04-09 at 15 32 27" src="https://github.com/Ajaxy/telegram-tt/assets/47010047/89cdf0b4-d7ae-4348-8897-4d121be6b8af">

<img width="236" alt="Screenshot 2024-04-09 at 15 33 08" src="https://github.com/Ajaxy/telegram-tt/assets/47010047/dfe36a2e-2e84-4c78-9643-d1fc785d47bd">

4. Another chat с большой буквы

<img width="267" alt="Screenshot 2024-04-09 at 15 36 09" src="https://github.com/Ajaxy/telegram-tt/assets/47010047/97d635a2-0522-42d9-9ae3-f07ef38f9e5e">

2024-04-09 13:10 UTC, Ajaxy requested changes

2024-04-09 13:10 UTC, Ajaxy commented on src/components/middle/composer/ComposerEmbeddedMessage.tsx
> +  isReplyContainsQuote?: boolean;
`doesReplyContainQuote`, а ещё лучше просто `isReplyWithQuote`.

2024-04-09 13:10 UTC, Ajaxy commented on src/components/middle/composer/ComposerEmbeddedMessage.tsx
>      focusMessage({ chatId: message!.chatId, messageId: message!.id, noForumTopicPanel: true });
Наверное, если открыли контекстное меню, то фокус уже делать не надо? Внутри меню ведь есть Show Message.

2024-04-09 13:10 UTC, Ajaxy commented on src/components/middle/composer/ComposerEmbeddedMessage.tsx
> +  const baseClickHandler = (
Лучше назвать `buildMenuItemHandler`.

2024-04-09 13:10 UTC, Ajaxy commented on src/components/middle/composer/ComposerEmbeddedMessage.tsx
> +  const baseClickHandler = (
А вообще, кажется можно использовать проп `autoClose` для `Menu`.

2024-04-09 13:10 UTC, Ajaxy commented on src/components/middle/composer/ComposerEmbeddedMessage.tsx
> +  const baseClickHandler = (
И сделать что-то вроде
```ts
const handleMenuClose = useLastCallback(() => {
  handleContextMenuClose();
  e.stopPropagation();
});
```

2024-04-09 13:10 UTC, Ajaxy commented on src/components/middle/composer/ComposerEmbeddedMessage.tsx
> +  const baseClickHandler = (
Либо можно сделать ещё лучше: в `MenuItem` добавить проп `withAutoStopPropagation`.

2024-04-09 13:10 UTC, Ajaxy commented on src/components/middle/composer/ComposerEmbeddedMessage.tsx
> +  const handleForwardAnotherChatClick = useLastCallback(baseClickHandler(changeForwardRecipient));
→ `handleForwardToAnotherChatClick`

2024-04-09 13:10 UTC, Ajaxy commented on src/components/middle/composer/ComposerEmbeddedMessage.tsx
> +      isReplyContainsQuote,
Это можно перенести внутрь компонента, т.к. `replyInfo` уже передаётся туда.

2024-04-09 13:10 UTC, Ajaxy commented on src/global/selectors/messages.ts
> +export function replyContainVoiceMessages<T extends GlobalState>(
→ `selectReplyContainsVoiceMessages`

2024-04-09 13:10 UTC, Ajaxy commented on src/global/selectors/messages.ts
> +  const opt = getAllowedAttachmentOptions(chat, chatFullInfo);
opt → options (сокращения не используем).

2024-04-09 13:10 UTC, Ajaxy commented on src/global/actions/api/messages.ts
> +  actions.moveCurrentReplyToNewDraft({ chatId, threadId: topicId || MAIN_THREAD_ID });
А для чего это вынесено в отдельный экшн? Если это существует только в рамках `openChatOrTopicWithReplyInDraft`, может, просто вынести в обычную функцию?

2024-04-09 13:10 UTC, Ajaxy commented on src/global/actions/ui/messages.ts
> +addActionHandler('changeReplyRecipient', (global, actions, payload): ActionReturnType => {
Этот экшн полностью копирует `changeForwardRecipient`, может сделать `changeRecipient` просто? Или, `changeReplyOrForwardRecipient`, или `changeDraftRecipient`.

2024-06-04 17:22 UTC, closed without merging